### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/broomstick#1]
:smile:

**Comment by tasomaniac** [comment]
Should we delete this? @mauimauer @friedger @Splaktar

**Comment by mauimauer** [comment]
no :D

**Comment by tasomaniac** [comment]
What is it for? I am curious :)

**Comment by friedger** [comment]
@mauimauer Is gitbook good enough to delete this?

**Comment by mauimauer** [comment]
Seriously...go ahead delete it.
